### ISSUE TITLE
Use of Deprecated APIs

### ISSUE THREAD

**Issue by JeffryBooher** [peterflynn/brackets-editor-nav#5]
This extension is using `DocumentManager.getWorkingSet()` which has been deprecated.

Also, this extension does not navigate to the next file in the working set when the currently selected file  is an image because it's using `DocumentManager.getCurrentDocument()` which returns `null` for images.

**Comment by JeffryBooher** [comment]
See https://github.com/adobe/brackets/issues/10470

**Comment by peterflynn** [comment]
Fixed in version 1.1
